# Generated by Django 3.2.16 on 2024-07-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240728_1826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersPosts',
        ),
    ]
